### ISSUE TITLE
Update docs for IP behavior on local Kubernetes configurations

### ISSUE THREAD

**Issue by ytimocin** [radius-project/docs#79]
For Kubernetes clusters like Kind, k3d, minikube, etc. the deployment doesn't produce a public IP. There are a few solutions here:
1. Set up Kubernetes cluster to expose host and port for the application by default so that it is publicly accessible. An example by @willdavsmith for Kind configuration before creating a cluster:
```
# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
```
2. If Kubernetes is configured with the default configuration, there is a command that could be run after the deployment: `rad resource expose Container frontend -a todoapp --port 3000` (You can change 3000 to the port where your app is running)

The docs should be updated accordingly.
